# Generated by Django 4.0.5 on 2022-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_actor_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
