# Generated by Django 4.0.5 on 2022-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_alter_actor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
